export type UiLanguage = 'en' | 'zh';

const storageKey = 'robot-log-ui-language';
let language: UiLanguage = localStorage.getItem(storageKey) === 'zh' ? 'zh' : 'en';
const listeners = new Set<(language: UiLanguage) => void>();

const zh: Record<string, string> = {
  'LOCAL LOG PREPROCESSOR': '本地日志预处理器', 'Robot log workbench': '机器人日志工作台',
  'Prepare logs locally, download a compact analysis brief, and retrieve more context when needed. No model calls or tokens are used during preprocessing.': '在本地预处理日志，下载精简分析摘要，并按需读取更多上下文。预处理期间不会调用模型或使用令牌。',
  '1. Upload compressed logs': '1. 上传压缩日志', INPUT: '输入', 'Original files stay local during preprocessing. Creating shared analysis uploads selected originals and evidence to the backend.': '预处理期间原始文件保留在本地。创建共享分析会将所选原始文件和证据上传到后端。', 'Choose folder': '选择文件夹', 'Add files or archives': '添加文件或归档', 'No files selected.': '尚未选择文件。', 'Reads TAR.GZ/TGZ/TAR, GZ, ZIP, text logs and configuration metadata. Binary MCAP/ROS recordings are inventoried as unsupported.': '支持 TAR.GZ/TGZ/TAR、GZ、ZIP、文本日志和配置元数据。二进制 MCAP/ROS 记录将被列为不支持。', 'The brief is capped at 16 KB, not an exact token count. Export JSON includes the larger local evidence package.': '摘要上限为 16 KB，并非精确令牌数。导出的 JSON 包含更完整的本地证据包。',
  'Preprocess logs': '预处理日志', 'Cancel run': '取消运行', 'Export JSON': '导出 JSON', 'Download analysis brief': '下载分析摘要', '2. Run status': '2. 运行状态', WORKER: '工作器', 'Ready for local input.': '可开始本地输入。', 'Ready for local preprocessing.': '可开始本地预处理。', 'Worker is preprocessing selected sources locally.': '工作器正在本地预处理所选来源。', 'Local preprocessing complete. Export is available on request.': '本地预处理完成。可按需导出。', 'Run cancelled': '运行已取消', 'Run cancelled. No partial package is available for export.': '运行已取消。没有可导出的部分结果包。', 'No active file.': '没有活动文件。', '3. Bounded results': '3. 有界结果', EVIDENCE: '证据', 'Results will appear after a successful local preprocessing run.': '本地预处理成功后将在此显示结果。', 'Read original context': '读取原始上下文', 'Choose any readable file and line, including events absent from the brief. Archives are streamed again locally. Keep this page open; the exported brief alone cannot access original files.': '选择任意可读取的文件和行，包括摘要未包含的事件。归档会在本地再次流式读取。请保持本页打开；仅凭导出的摘要无法访问原始文件。', 'Read 20 lines': '读取 20 行', 'Next page': '下一页', 'Cancel context': '取消上下文读取', 'Download context': '下载上下文', 'Each response is capped at 12 KB.': '每次响应上限为 12 KB。',
  '4. Shared analysis queue': '4. 共享分析队列', SHARED: '共享', 'Checking backend…': '正在检查后端…', 'Backend connected': '后端已连接', 'Backend offline — local preprocessing still works.': '后端离线——本地预处理仍可使用。', 'Analysis request': '分析请求', 'Output language': '输出语言', English: '英语', 'Attach images or PDFs': '附加图片或 PDF', 'Browser feedback limit: 25 attachments / 250 MB. Server validation still applies.': '浏览器提示上限：25 个附件 / 250 MB。服务器仍会验证。', 'I understand that creating shared analysis uploads selected original files, full evidence, and attachments to the shared backend.': '我了解创建共享分析会将所选原始文件、完整证据和附件上传到共享后端。', 'Create shared analysis': '创建共享分析', 'All analysis jobs': '所有分析任务', 'Load older jobs': '加载更早任务', 'Load final report': '加载最终报告', 'No final report available': '暂无最终报告', 'No shared jobs yet.': '暂无共享任务。', 'Wait for selected logs to finish local preprocessing.': '请等待所选日志完成本地预处理。', 'Selected logs require a fresh local preprocessing run.': '所选日志需要重新进行本地预处理。', 'Choose logs or an image/PDF attachment.': '请选择日志或图片/PDF 附件。', 'Reviewer name': '审核人姓名', queued: '排队中', running: '运行中', uploading: '上传中', stopping: '停止中', completed: '已完成', failed: '失败', cancelled: '已取消', 'Loading sanitized agent activity…': '正在加载已净化的代理活动…', 'Agent activity unavailable.': '代理活动暂不可用。', 'Final report': '最终报告', 'Hard stop': '强制停止', 'Claim review': '认领审核', 'Review claimed': '审核已认领', 'Forget stale claim': '忘记过期认领', 'Save immutable review & release': '保存不可变审核并释放', 'Immutable review versions': '不可变审核版本', Success: '成功', 'Not successful': '未成功', 'Why: ': '原因：', 'Edited debug procedure: ': '修改后的调试步骤：', 'Why is this review outcome correct?': '此审核结论为何正确？', 'Edited debug procedure': '修改后的调试步骤', 'Analysis worker/model unavailable: the queue API is available, but real analysis requires a separately configured worker and model.': '分析工作器/模型不可用：队列 API 可用，但真实分析需要单独配置工作器和模型。',
};
const originals = new WeakMap<Text, string>();
export function uiLanguage(): UiLanguage { return language; }
export function setUiLanguage(next: UiLanguage): void { language = next; localStorage.setItem(storageKey, next); for (const listener of listeners) listener(next); }
export function onUiLanguage(listener: (next: UiLanguage) => void): () => void { listeners.add(listener); return () => listeners.delete(listener); }
export function translate(value: string): string { return language === 'zh' ? zh[value] ?? value : value; }
export function setUiText(element: HTMLElement, source: string): void { element.dataset.i18nSource = source; element.textContent = translate(source); }
export function translateTree(root: Node): void { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let current: Node | null; while ((current = walker.nextNode())) { const text = current as Text, parent = text.parentElement; if (parent?.closest('[data-i18n-skip], pre, code')) continue; const source = parent?.dataset.i18nSource ?? originals.get(text) ?? text.data; originals.set(text, source); text.data = translate(source); } }
